### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by mzaini30** [arrizalamin/besutkode1#1]
Input: `besutkode1 en_US.po `

Output:

```
/usr/local/lib/node_modules/besutkode1/index.js:4
const {argv} = require('optimist')
      ^
SyntaxError: Unexpected token {
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

**Comment by arrizalamin** [comment]
that's because node.js version 4 or 5 doesn't support destructuring, try upgrading to version 6
